// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TgBotClient is the client API for TgBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgBotClient interface {
	GetMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error)
}

type tgBotClient struct {
	cc grpc.ClientConnInterface
}

func NewTgBotClient(cc grpc.ClientConnInterface) TgBotClient {
	return &tgBotClient{cc}
}

func (c *tgBotClient) GetMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/api.tgBot/GetMess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgBotServer is the server API for TgBot service.
// All implementations must embed UnimplementedTgBotServer
// for forward compatibility
type TgBotServer interface {
	GetMess(context.Context, *MessReq) (*StatusResp, error)
	mustEmbedUnimplementedTgBotServer()
}

// UnimplementedTgBotServer must be embedded to have forward compatible implementations.
type UnimplementedTgBotServer struct {
}

func (UnimplementedTgBotServer) GetMess(context.Context, *MessReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMess not implemented")
}
func (UnimplementedTgBotServer) mustEmbedUnimplementedTgBotServer() {}

// UnsafeTgBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgBotServer will
// result in compilation errors.
type UnsafeTgBotServer interface {
	mustEmbedUnimplementedTgBotServer()
}

func RegisterTgBotServer(s grpc.ServiceRegistrar, srv TgBotServer) {
	s.RegisterService(&TgBot_ServiceDesc, srv)
}

func _TgBot_GetMess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgBotServer).GetMess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.tgBot/GetMess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgBotServer).GetMess(ctx, req.(*MessReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TgBot_ServiceDesc is the grpc.ServiceDesc for TgBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tgBot",
	HandlerType: (*TgBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMess",
			Handler:    _TgBot_GetMess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "new.proto",
}
