// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TgBotClient is the client API for TgBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgBotClient interface {
	SendMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error)
}

type tgBotClient struct {
	cc grpc.ClientConnInterface
}

func NewTgBotClient(cc grpc.ClientConnInterface) TgBotClient {
	return &tgBotClient{cc}
}

func (c *tgBotClient) SendMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/api.tgBot/SendMess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgBotServer is the server API for TgBot service.
// All implementations must embed UnimplementedTgBotServer
// for forward compatibility
type TgBotServer interface {
	SendMess(context.Context, *MessReq) (*StatusResp, error)
	mustEmbedUnimplementedTgBotServer()
}

// UnimplementedTgBotServer must be embedded to have forward compatible implementations.
type UnimplementedTgBotServer struct {
}

func (UnimplementedTgBotServer) SendMess(context.Context, *MessReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMess not implemented")
}
func (UnimplementedTgBotServer) mustEmbedUnimplementedTgBotServer() {}

// UnsafeTgBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgBotServer will
// result in compilation errors.
type UnsafeTgBotServer interface {
	mustEmbedUnimplementedTgBotServer()
}

func RegisterTgBotServer(s grpc.ServiceRegistrar, srv TgBotServer) {
	s.RegisterService(&TgBot_ServiceDesc, srv)
}

func _TgBot_SendMess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgBotServer).SendMess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.tgBot/SendMess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgBotServer).SendMess(ctx, req.(*MessReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TgBot_ServiceDesc is the grpc.ServiceDesc for TgBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tgBot",
	HandlerType: (*TgBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMess",
			Handler:    _TgBot_SendMess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "new.proto",
}

// SmtpClIClient is the client API for SmtpClI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmtpClIClient interface {
	SendMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error)
}

type smtpClIClient struct {
	cc grpc.ClientConnInterface
}

func NewSmtpClIClient(cc grpc.ClientConnInterface) SmtpClIClient {
	return &smtpClIClient{cc}
}

func (c *smtpClIClient) SendMess(ctx context.Context, in *MessReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/api.smtpClI/SendMess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmtpClIServer is the server API for SmtpClI service.
// All implementations must embed UnimplementedSmtpClIServer
// for forward compatibility
type SmtpClIServer interface {
	SendMess(context.Context, *MessReq) (*StatusResp, error)
	mustEmbedUnimplementedSmtpClIServer()
}

// UnimplementedSmtpClIServer must be embedded to have forward compatible implementations.
type UnimplementedSmtpClIServer struct {
}

func (UnimplementedSmtpClIServer) SendMess(context.Context, *MessReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMess not implemented")
}
func (UnimplementedSmtpClIServer) mustEmbedUnimplementedSmtpClIServer() {}

// UnsafeSmtpClIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmtpClIServer will
// result in compilation errors.
type UnsafeSmtpClIServer interface {
	mustEmbedUnimplementedSmtpClIServer()
}

func RegisterSmtpClIServer(s grpc.ServiceRegistrar, srv SmtpClIServer) {
	s.RegisterService(&SmtpClI_ServiceDesc, srv)
}

func _SmtpClI_SendMess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmtpClIServer).SendMess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.smtpClI/SendMess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmtpClIServer).SendMess(ctx, req.(*MessReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SmtpClI_ServiceDesc is the grpc.ServiceDesc for SmtpClI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmtpClI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.smtpClI",
	HandlerType: (*SmtpClIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMess",
			Handler:    _SmtpClI_SendMess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "new.proto",
}
